# Copyright 2024 <lhearachel@proton.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
.PHONY: check-dep-exists format test test-rewrite docs

check-all: format pre-commit

check-dep-exists:
	@if ! command -v $(DEP_TARGET) &> /dev/null; then \
		echo "$(DEP_TARGET) not found"; \
		exit 1; \
	fi

format: DEP_TARGET=clang-format
format: .clang-format check-dep-exists
	clang-format -i --style=file $(SRC) $(INC)

test: tools/runtests.py release
	@$< help $(ARGS)
	@$< version $(ARGS)
	@$< enum $(ARGS)
	@$< mask $(ARGS)

test-rewrite: tools/runtests.py release
	$< --rewrite help
	$< --rewrite version
	$< --rewrite enum
	$< --rewrite mask

README_TEMPLATE = docs/README.md.template
ENUM_BASE_TEST = tests/enum/base.test
ENUM_BASE_PY_TEST = tests/enum/lang_py.test
MAN_MD = docs/man.md
GEN_DOCS = tools/gen_docs.py

docs: $(README_TEMPLATE) $(VERSION) $(ENUM_BASE_TEST) $(ENUM_BASE_PY_TEST) $(TARGET) $(MAN_MD)
	$(GEN_DOCS) $^
