// SPDX-License-Identifier: MIT

#include "langs/c.h"

#include <libgen.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "global.h"

#include "libs/strings.h"
#include "libs/vector.h"

static int seqelemcmp(const void *a, const void *b);

void c_pregen(FILE *stream, vector *sequence, args *args)
{
    unused(sequence);

    const char *infname = args->infname ? (char *)args->infname : "stdin";
    args->infbase       = strmake(basename((char *)infname));
    args->infbaseup     = strupper(args->infbase);
    args->guard         = strupper(string(args->inguard, strlen(args->inguard)));
    args->tag           = args->intag ? strmake(args->intag) : strcut(args->infbase, '.').head;

    fprintf(stream, "/*\n");
    fprintf(stream, " * This file was generated by metang; DO NOT MODIFY IT!!\n");
    fprintf(stream, " * \n");
    fprintf(stream, " * Source file: %s\n", infname);
    fprintf(stream, " * Reproducible options:\n");
    fprintf(stream, " *   --lang %s\n", args->lang);
    fprintf(stream, " *   --guard %.*s\n", fmtstring(args->guard));
    fprintf(stream, " *   --tag %.*s\n", fmtstring(args->tag));
    fprintf(stream, " */\n");
    fprintf(stream, "\n");
    fprintf(stream, "#ifndef %.*s_%.*s\n", fmtstring(args->guard), fmtstring(args->infbaseup));
    fprintf(stream, "#define %.*s_%.*s\n", fmtstring(args->guard), fmtstring(args->infbaseup));
    fprintf(stream, "\n");
    fprintf(stream, "#ifdef __cplusplus\n");
    fprintf(stream, "extern \"C\" {\n");
    fprintf(stream, "#endif\n");
    fprintf(stream, "\n");
}

void c_gen(FILE *stream, vector *sequence, args *args)
{
    fprintf(stream, "#ifdef %.*s_ENUM\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(stream, "enum %.*s {\n", fmtstring(args->tag));

    for (int i = 0; i < sequence->len; i++) {
        seqelem *elem = get(sequence, seqelem, i);
        fprintf(stream, "    %.*s = %ld,\n", fmtstring(elem->symbol), elem->value);
    }

    fprintf(stream, "}; /* enum %.*s */\n", fmtstring(args->tag));
    fprintf(stream, "\n");
    fprintf(stream, "#else  /* %.*s_ENUM */\n", fmtstring(args->guard));
    fprintf(stream, "\n");

    for (int i = 0; i < sequence->len; i++) {
        seqelem *elem = get(sequence, seqelem, i);
        fprintf(stream, "#define %.*s %ld\n", fmtstring(elem->symbol), elem->value);
    }

    fprintf(stream, "\n");
    fprintf(stream, "#endif /* %.*s_ENUM */\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(stream, "#ifdef %.*s_LOOKUP\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(stream, "typedef struct entry__%.*s {\n", fmtstring(args->tag));
    fprintf(stream, "    const char *name;\n");
    fprintf(stream, "    const long value;\n");
    fprintf(stream, "} entry__%.*s;\n", fmtstring(args->tag));
    fprintf(stream, "\n");
    fprintf(stream, "#ifdef %.*s_LOOKUP_IMPL\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(stream, "const long lengthof__%.*s = %d;\n", fmtstring(args->tag), sequence->len);
    fprintf(
        stream,
        "const entry__%.*s lookup__%.*s[] = {\n",
        fmtstring(args->tag),
        fmtstring(args->tag)
    );

    // We are done with output for the enum at this stage, so we can resort it without consequence.
    qsort(sequence->data, sequence->len, sizeof(seqelem), seqelemcmp);
    for (int i = 0; i < sequence->len; i++) {
        seqelem *elem = get(sequence, seqelem, i);
        fprintf(
            stream,
            "    { \"%.*s\", %.*s },\n",
            fmtstring(elem->symbol),
            fmtstring(elem->symbol)
        );
    }

    fprintf(stream, "};\n");
    fprintf(stream, "\n");
    fprintf(stream, "#else  /* %.*s_LOOKUP_IMPL */\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(stream, "extern const long lengthof__%.*s;\n", fmtstring(args->tag));
    fprintf(
        stream,
        "extern const entry__%.*s lookup__%.*s[];\n",
        fmtstring(args->tag),
        fmtstring(args->tag)
    );
    fprintf(stream, "\n");
    fprintf(stream, "#endif /* %.*s_LOOKUP_IMPL */\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(stream, "#endif /* %.*s_LOOKUP */\n", fmtstring(args->guard));
    fprintf(stream, "\n");
}

void c_postgen(FILE *stream, vector *sequence, args *args)
{
    unused(sequence);

    fprintf(stream, "#ifdef __cplusplus\n");
    fprintf(stream, "}\n");
    fprintf(stream, "#endif\n");
    fprintf(stream, "\n");
    fprintf(stream, "#endif /* %.*s_%.*s */\n", fmtstring(args->guard), fmtstring(args->infbaseup));
}

static int seqelemcmp(const void *a, const void *b) // NOLINT: bugprone-easily-swappable-parameters
{
    const seqelem *elem_a = a;
    const seqelem *elem_b = b;
    return strcmp((char *)elem_a->symbol.s, (char *)elem_b->symbol.s);
}
