// SPDX-License-Identifier: MIT

#include "langs/c.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "global.h"

#include "libs/strings.h"
#include "libs/vector.h"

static int seqelemcmp(const void *a, const void *b);

void c_pregen(FILE *stream, sequence *seq, args *args)
{
    unused(seq);

    fprintf(stream, "/*\n");
    fprintf(stream, " * This file was generated by metang; DO NOT MODIFY IT!!\n");
    fprintf(stream, " * \n");
    fprintf(stream, " * Source file: %s\n", args->infname ? args->infname : "stdin");
    fprintf(stream, " * Reproducible options:\n");
    if (args->bitmask) fprintf(stream, " *   --bitmask\n");
    fprintf(stream, " *   --lang %s\n", args->lang);
    fprintf(stream, " *   --guard %.*s\n", fmtstring(args->guard));
    fprintf(stream, " *   --tag %.*s\n", fmtstring(args->tag));
    fprintf(stream, " */\n");
    fprintf(stream, "\n");
    fprintf(stream, "#ifndef %.*s_%.*s\n", fmtstring(args->guard), fmtstring(args->infbaseup));
    fprintf(stream, "#define %.*s_%.*s\n", fmtstring(args->guard), fmtstring(args->infbaseup));
    fprintf(stream, "\n");
    fprintf(stream, "#ifdef __cplusplus\n");
    fprintf(stream, "extern \"C\" {\n");
    fprintf(stream, "#endif\n");
    fprintf(stream, "\n");
}

#define pad(__elem)   (int)(seq->maxsymlen - (__elem)->symbol.len), ""
#define elem0(__elem) fmtstring((__elem)->symbol), pad(__elem), (__elem)->value
#define elem(__elem)  fmtstring((__elem)->symbol), pad(__elem), (__elem)->value - args->bitmask

void c_gen(FILE *stream, sequence *seq, args *args)
{
    fprintf(stream, "#ifdef %.*s_ENUM\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(stream, "enum %.*s {\n", fmtstring(args->tag));

    const char *enum_fmt, *proc_fmt, *last_enum_fmt, *last_proc_fmt;
    if (args->bitmask) {
        enum_fmt      = "    %.*s %*s= (1 << %ld),\n";
        proc_fmt      = "#define %.*s %*s(1 << %ld)\n";
        last_enum_fmt = "    %.*s %*s= ((1 << %ld) - 1),\n";
        last_proc_fmt = "#define %.*s %*s((1 << %ld) - 1)\n";
    } else {
        enum_fmt      = "    %.*s %*s= %ld,\n";
        proc_fmt      = "#define %.*s %*s%ld\n";
        last_enum_fmt = "    %.*s = %*s%ld,\n";
        last_proc_fmt = "#define %.*s %*s%ld\n";
    }

    seqelem *first = get(&seq->elems, seqelem, 0);
    seqelem *last  = get(&seq->elems, seqelem, seq->elems.len - 1);

    fprintf(stream, "    %.*s %*s= %ld,\n", elem0(first));
    for (int i = 1; i < seq->elems.len - 1; i++) {
        seqelem *elem = get(&seq->elems, seqelem, i);
        fprintf(stream, enum_fmt, elem(elem));
    }
    fprintf(stream, last_enum_fmt, elem(last));

    fprintf(stream, "}; /* enum %.*s */\n", fmtstring(args->tag));
    fprintf(stream, "\n");
    fprintf(stream, "#else  /* %.*s_ENUM */\n", fmtstring(args->guard));
    fprintf(stream, "\n");

    fprintf(stream, "#define %.*s %*s%ld\n", elem0(first));
    for (int i = 1; i < seq->elems.len - 1; i++) {
        seqelem *elem = get(&seq->elems, seqelem, i);
        fprintf(stream, proc_fmt, elem(elem));
    }
    fprintf(stream, last_proc_fmt, elem(last));

    fprintf(stream, "\n");
    fprintf(stream, "#endif /* %.*s_ENUM */\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(stream, "#ifdef %.*s_LOOKUP\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(stream, "typedef struct entry__%.*s {\n", fmtstring(args->tag));
    fprintf(stream, "    const char *name;\n");
    fprintf(stream, "    const long value;\n");
    fprintf(stream, "} entry__%.*s;\n", fmtstring(args->tag));
    fprintf(stream, "\n");
    fprintf(stream, "#ifdef %.*s_LOOKUP_IMPL\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(stream, "const long lengthof__%.*s = %d;\n", fmtstring(args->tag), seq->elems.len);
    fprintf(
        stream,
        "const entry__%.*s lookup__%.*s[] = {\n",
        fmtstring(args->tag),
        fmtstring(args->tag)
    );

    // We are done with output for the enum at this stage, so we can resort it without consequence.
    qsort(seq->elems.data, seq->elems.len, sizeof(seqelem), seqelemcmp);
    for (int i = 0; i < seq->elems.len; i++) {
        seqelem *elem = get(&seq->elems, seqelem, i);
        fprintf(
            stream,
            "    { \"%.*s\", %*s%.*s %*s},\n",
            fmtstring(elem->symbol),
            pad(elem),
            fmtstring(elem->symbol),
            pad(elem)
        );
    }

    fprintf(stream, "};\n");
    fprintf(stream, "\n");
    fprintf(stream, "#else  /* %.*s_LOOKUP_IMPL */\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(stream, "extern const long lengthof__%.*s;\n", fmtstring(args->tag));
    fprintf(
        stream,
        "extern const entry__%.*s lookup__%.*s[];\n",
        fmtstring(args->tag),
        fmtstring(args->tag)
    );
    fprintf(stream, "\n");
    fprintf(stream, "#endif /* %.*s_LOOKUP_IMPL */\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(stream, "#endif /* %.*s_LOOKUP */\n", fmtstring(args->guard));
    fprintf(stream, "\n");
}

void c_postgen(FILE *stream, sequence *seq, args *args)
{
    unused(seq);

    fprintf(stream, "#ifdef __cplusplus\n");
    fprintf(stream, "}\n");
    fprintf(stream, "#endif\n");
    fprintf(stream, "\n");
    fprintf(stream, "#endif /* %.*s_%.*s */\n", fmtstring(args->guard), fmtstring(args->infbaseup));
}

static int seqelemcmp(const void *a, const void *b) // NOLINT: bugprone-easily-swappable-parameters
{
    const seqelem *elem_a = a;
    const seqelem *elem_b = b;
    return strcmp((char *)elem_a->symbol.s, (char *)elem_b->symbol.s);
}
