#include "langs/c.h"

#include <libgen.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "global.h"

#include "libs/strings.h"
#include "libs/vector.h"

static char *strupper(const char *s);

void c_pregen(FILE *stream, vector *sequence, args *args)
{
    unused(sequence);

    const char *infname = args->infname ? (char *)args->infname : "stdin";
    const char *infbase = basename((char *)infname);
    args->upperbase     = strupper(infbase);
    args->guard         = strupper(args->inguard);

    fprintf(stream, "/*\n");
    fprintf(stream, " * This file was generated by metang; DO NOT MODIFY IT!!\n");
    fprintf(stream, " * Source file: %s\n", infname);
    fprintf(stream, " * Program options:\n");
    fprintf(stream, " *   --lang %s\n", args->lang);
    fprintf(stream, " *   --guard %s\n", args->inguard);
    if (args->tag) fprintf(stream, " *   --tag %s\n", args->tag);
    if (args->outfname) fprintf(stream, " *   --output %s\n", args->outfname);
    fprintf(stream, " */\n");
    fprintf(stream, "\n");
    fprintf(stream, "#ifndef %s_%s\n", args->guard, args->upperbase);
    fprintf(stream, "#define %s_%s\n", args->guard, args->upperbase);
    fprintf(stream, "\n");
    fprintf(stream, "#ifdef __cplusplus\n");
    fprintf(stream, "extern \"C\" {\n");
    fprintf(stream, "#endif\n");
    fprintf(stream, "\n");
}

void c_gen(FILE *stream, vector *sequence, args *args)
{
    unused(args);

    for (int i = 0; i < sequence->len; i++) {
        seqelem *elem = get(sequence, seqelem, i);
        fprintf(stream, "%.*s -> %ld\n", fmtstring(elem->symbol), elem->value);
    }

    fprintf(stream, "\n");
}

void c_postgen(FILE *stream, vector *sequence, args *args)
{
    unused(sequence);

    fprintf(stream, "#ifdef __cplusplus\n");
    fprintf(stream, "}\n");
    fprintf(stream, "#endif\n");
    fprintf(stream, "\n");
    fprintf(stream, "#endif /* %s_%s */\n", args->guard, args->upperbase);
}

static char *strupper(const char *s)
{
    char       *upper = malloc(strlen(s) + 1);
    const char *p     = s;
    char       *u     = upper;

    for (; *p; p++, u++) {
        if (*p >= 'a' && *p <= 'z') *u = (char)(*p - ('a' - 'A'));
        else if (*p < '0' || (*p > '9' && *p < 'A') || *p > 'Z') *u = '_';
        else *u = *p;
    }

    *u = '\0';
    return upper;
}
