// SPDX-License-Identifier: MIT

#include "langs/cpp.h"

#include <stdio.h>

#include "global.h"

#include "libs/strings.h"
#include "libs/vector.h"

void cpp_pregen(FILE *stream, sequence *seq, args *args)
{
    unused(seq);

    fprintf(stream, "/*\n");
    fprintf(stream, " * This file was generated by metang; DO NOT MODIFY IT!!\n");
    fprintf(stream, " *\n");
    fprintf(stream, " * Source file: %s\n", args->infname ? args->infname : "stdin");
    fprintf(stream, " * Reproducible options:\n");
    if (args->bitmask) fprintf(stream, " *   --bitmask\n");
    fprintf(stream, " *   --lang %s\n", args->lang);
    fprintf(stream, " *   --guard %.*s\n", fmtstring(args->guard));
    fprintf(stream, " *   --tag %.*s\n", fmtstring(args->tag));
    fprintf(stream, " */\n");
    fprintf(stream, "\n");
    fprintf(stream, "#pragma once\n");
    fprintf(stream, "\n");
}

#define pad(__elem)   (int)(seq->maxsymlen - (__elem)->symbol.len), ""
#define elem0(__elem) fmtstring((__elem)->symbol), pad(__elem), (__elem)->value
#define elem(__elem)  fmtstring((__elem)->symbol), pad(__elem), (__elem)->value - args->bitmask

// clang-format off
static const char *enumtypes[] = {
    [S_unbound]        = "",
    [S_unsigned_8bit]  = ": std::uint8_t",
    [S_unsigned_16bit] = ": std::uint16_t",
    [S_unsigned_32bit] = ": std::uint32_t",
    [S_unsigned_64bit] = ": std::uint64_t",
    [S_signed_8bit]    = ": std::int8_t",
    [S_signed_16bit]   = ": std::int16_t",
    [S_signed_32bit]   = ": std::int32_t",
    [S_signed_64bit]   = ": std::int64_t",
};
// clang-format on

void cpp_gen(FILE *stream, sequence *seq, args *args)
{
    unused(seq);

    fprintf(stream, "#if __cplusplus >= 201103L\n"); // C++11: support for enum struct and base type
    fprintf(stream, "#  include <cstdint>\n");
    fprintf(
        stream,
        "#  define %.*s_ENUM_QUAL_%.*s struct\n",
        fmtstring(args->guard),
        fmtstring(args->tag)
    );
    fprintf(
        stream,
        "#  define %.*s_ENUM_BASE_%.*s %s\n",
        fmtstring(args->guard),
        fmtstring(args->tag),
        enumtypes[args->sizesign]
    );
    fprintf(stream, "#else\n");
    fprintf(
        stream,
        "#  define %.*s_ENUM_QUAL_%.*s\n",
        fmtstring(args->guard),
        fmtstring(args->tag)
    );
    fprintf(
        stream,
        "#  define %.*s_ENUM_BASE_%.*s\n",
        fmtstring(args->guard),
        fmtstring(args->tag)
    );
    fprintf(stream, "#endif\n");
    fprintf(stream, "\n");

    fprintf(
        stream,
        "enum %.*s_ENUM_QUAL_%.*s %.*s %.*s_ENUM_BASE_%.*s {\n",
        fmtstring(args->guard),
        fmtstring(args->tag),
        fmtstring(args->tag),
        fmtstring(args->guard),
        fmtstring(args->tag)
    );

    const char *fmt, *last_fmt;
    if (args->bitmask) {
        fmt      = "    %.*s %*s= (1 << %ld),\n";
        last_fmt = "    %.*s %*s= ((1 << %ld) - 1),\n";
    } else {
        fmt      = "    %.*s %*s= %ld,\n";
        last_fmt = "    %.*s = %*s%ld,\n";
    }

    seqelem *first = get(&seq->elems, seqelem, 0);
    seqelem *last  = get(&seq->elems, seqelem, seq->elems.len - 1);

    fprintf(stream, "    %.*s %*s= %ld,\n", elem0(first));
    for (int i = 1; i < seq->elems.len - 1; i++) {
        seqelem *elem = get(&seq->elems, seqelem, i);
        fprintf(stream, fmt, elem(elem));
    }
    fprintf(stream, last_fmt, elem(last));

    fprintf(stream, "};\n");
    fprintf(stream, "\n");
}

void cpp_postgen(FILE *stream, sequence *seq, args *args)
{
    unused(seq);

    fprintf(stream, "#ifdef %.*s_LOOKUP\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(stream, "#include <map>\n");
    fprintf(stream, "#include <string>\n");
    fprintf(stream, "\n");
    fprintf(stream, "#ifdef %.*s_LOOKUP_IMPL\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(
        stream,
        "const std::map<std::string, %.*s> lookup_%.*s = {\n",
        fmtstring(args->tag),
        fmtstring(args->tag)
    );

    for (int i = 0; i < seq->elems.len; i++) {
        seqelem *elem = get(&seq->elems, seqelem, i);
        fprintf(
            stream,
            "    { \"%.*s\", %*s%.*s::%.*s %*s},\n",
            fmtstring(elem->symbol),
            pad(elem),
            fmtstring(args->tag),
            fmtstring(elem->symbol),
            pad(elem)
        );
    }

    fprintf(stream, "};\n");
    fprintf(stream, "\n");
    fprintf(stream, "#else // %.*s_LOOKUP_IMPL\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(
        stream,
        "extern const std::map<std::string, %.*s> lookup_%.*s;\n",
        fmtstring(args->tag),
        fmtstring(args->tag)
    );
    fprintf(stream, "\n");
    fprintf(stream, "#endif // %.*s_LOOKUP_IMPL\n", fmtstring(args->guard));
    fprintf(stream, "\n");
    fprintf(stream, "#endif // %.*s_LOOKUP\n", fmtstring(args->guard));
}
