// SPDX-License-Identifier: MIT

#include "langs/py.h"

#include "global.h"
#include "libs/strings.h"
#include "libs/vector.h"
#include <stdio.h>

void py_pregen(FILE *stream, sequence *seq, args *args)
{
    unused(seq);

    fprintf(stream, "\"\"\"\n");
    fprintf(stream, "    This file was generated by metang; DO NOT MODIFY IT!!\n");
    fprintf(stream, "\n");
    fprintf(stream, "    Source file: %s\n", args->infname ? args->infname : "stdin");
    fprintf(stream, "    Reproducible options:\n");
    if (args->bitmask) fprintf(stream, "      --bitmask\n");
    fprintf(stream, "      --lang %s\n", args->lang);
    fprintf(stream, "      --guard %.*s\n", fmtstring(args->guard));
    fprintf(stream, "      --tag %.*s\n", fmtstring(args->tag));
    fprintf(stream, "\"\"\"\n");
    fprintf(stream, "\n");
    fprintf(stream, "import enum\n");
    fprintf(stream, "\n");
}

#define pad(__elem)   (int)(seq->maxsymlen - (__elem)->symbol.len), ""
#define elem0(__elem) fmtstring((__elem)->symbol), pad(__elem), (__elem)->value
#define elem(__elem)  fmtstring((__elem)->symbol), pad(__elem), (__elem)->value - args->bitmask

void py_gen(FILE *stream, sequence *seq, args *args)
{
    fprintf(
        stream,
        "class %.*s(enum.%s):\n",
        fmtstring(args->tag),
        args->bitmask ? "IntFlag" : "IntEnum"
    );

    const char *fmt, *last_fmt;
    if (args->bitmask) {
        fmt      = "    %.*s %*s= (1 << %ld)\n";
        last_fmt = "    %.*s %*s= ((1 << %ld) - 1)\n";
    } else {
        fmt      = "    %.*s %*s= %ld\n";
        last_fmt = "    %.*s = %*s%ld\n";
    }

    const seqelem *first = get(&seq->elems, seqelem, 0);
    const seqelem *last  = get(&seq->elems, seqelem, seq->elems.len - 1);

    fprintf(stream, "    %.*s %*s= %ld\n", elem0(first));
    for (int i = 1; i < seq->elems.len - 1; i++) {
        seqelem *elem = get(&seq->elems, seqelem, i);
        fprintf(stream, fmt, elem(elem));
    }
    fprintf(stream, last_fmt, elem(last));
}

void py_postgen(FILE *stream, sequence *seq, args *args)
{
    unused(stream);
    unused(seq);
    unused(args);
}
