from textwrap import dedent
from typing import TextIO

from metang.mode import Mode
from metang.options import Options
from metang.util import snake


def _generate_enum_members_e(
    enum: list[tuple[str, int]], fout: TextIO, prefix: str, maxlen: int, digits: int
):
    for idt, val in enum:
        print(
            f"    {prefix}{idt: <{maxlen}} = {val: >{digits}},",
            file=fout,
        )


def _generate_mask_members_e(
    enum: list[tuple[str, int]], fout: TextIO, prefix: str, maxlen: int, digits: int
):
    print(
        f"    {prefix}{enum[0][0]: <{maxlen}} =       {0: >{digits}},",
        file=fout,
    )
    for idt, val in enum[1:]:
        print(
            f"    {prefix}{idt: <{maxlen}} = (1 << {val: >{digits}}),",
            file=fout,
        )


def _generate_enum_members_d(
    enum: list[tuple[str, int]], fout: TextIO, prefix: str, maxlen: int, digits: int
):
    for idt, val in enum:
        print(
            f"#define {prefix}{idt: <{maxlen}} {val: >{digits}}",
            file=fout,
        )


def _generate_mask_members_d(
    enum: list[tuple[str, int]], fout: TextIO, prefix: str, maxlen: int, digits: int
):
    print(
        f"#define {prefix}{enum[0][0]: <{maxlen}}       {0: >{digits}}",
        file=fout,
    )
    for idt, val in enum[1:]:
        print(
            f"#define {prefix}{idt: <{maxlen}} (1 << {val: >{digits}})",
            file=fout,
        )


def generate(enum: list[tuple[str, int]], opts: Options, maxlen: int, digits: int):
    prefix = "" if not opts.leader else f"{opts.leader}_"
    fout_name_snake = snake(opts.fout_name).upper()
    lookup = sorted(enum, key=lambda x: x[0])

    print(
        dedent(f"""
        /*
         * This file was generated by metang; DO NOT MODIFY IT!!
         * Base command: {"enum" if opts.mode & Mode.ENUM else "mask"}
         * Source file: {opts.fin_name}
         */

        #ifndef {opts.guard}_{fout_name_snake}
        #define {opts.guard}_{fout_name_snake}

        #ifndef __cplusplus
        extern "C" {{
        #endif

        #ifdef {opts.guard}_ENUM

        enum {opts.tag} {{"""),
        file=opts.fout,
    )

    if opts.mode & Mode.ENUM:
        _generate_enum_members_e(enum, opts.fout, prefix, maxlen, digits)
    else:
        _generate_mask_members_e(enum, opts.fout, prefix, maxlen, digits)

    print(f"}}; /* enum {opts.tag} */", file=opts.fout)
    print("", file=opts.fout)
    print("#else", file=opts.fout)
    print("", file=opts.fout)

    if opts.mode & Mode.ENUM:
        _generate_enum_members_d(enum, opts.fout, prefix, maxlen, digits)
    else:
        _generate_mask_members_d(enum, opts.fout, prefix, maxlen, digits)

    print(
        dedent(f"""
        #endif /* {opts.guard}_ENUM */

        #ifdef {opts.guard}_LOOKUP

        typdef struct entry__{opts.tag} {{
            const long value;
            const char *def;
        }} entry__{opts.tag};

        #ifndef {opts.guard}_LOOKUP_IMPL

        extern const long lengthof__{opts.tag};
        extern const entry__{opts.tag} lookup__{opts.tag}[];

        #else

        const long lengthof__{opts.tag} = {len(enum)};
        const entry__{opts.tag} lookup__{opts.tag}[] = {{"""),
        file=opts.fout,
    )

    for idt, _ in lookup:
        pad = " " * (maxlen - len(idt))
        print(f'    {{ {idt},{pad} "{idt}",{pad} }},', file=opts.fout)

    print(f"}}; /* lookup__{opts.tag}[] */", file=opts.fout)

    print(
        dedent(f"""
        #endif /* {opts.guard}_LOOKUP_IMPL */

        #endif /* {opts.guard}_LOOKUP */

        #ifdef __cplusplus
        }}
        #endif

        #endif /* {opts.guard}_{fout_name_snake} */"""),
        file=opts.fout,
    )
