from textwrap import dedent
from typing import TextIO

from metang.mode import Mode
from metang.options import Options


def _generate_enum_members(
    enum: list[tuple[str, int]], fout: TextIO, prefix: str, maxlen: int, digits: int
):
    for idt, val in enum:
        print(
            f"    {prefix}{idt: <{maxlen}} = {val: >{digits}}",
            file=fout,
        )


def _generate_mask_members(
    enum: list[tuple[str, int]], fout: TextIO, prefix: str, maxlen: int, digits: int
):
    print(
        f"    {prefix}{enum[0][0]: <{maxlen}} =       {0: >{digits}}",
        file=fout,
    )
    for idt, val in enum[1:-1]:
        print(
            f"    {prefix}{idt: <{maxlen}} = (1 << {val: >{digits}})",
            file=fout,
        )
    print(
        f"    {prefix}{enum[-1][0]: <{maxlen}} = ((1 << {enum[-1][1]: >{digits}}) - 1)",
        file=fout,
    )


def generate(enum: list[tuple[str, int]], opts: Options, maxlen: int, digits: int):
    print(
        dedent(f"""
        \"\"\"
            This file was generated by metang; DO NOT MODIFY IT!!
            Base command: {"enum" if opts.mode & Mode.ENUM else "mask"}
            Source file: {opts.fin_name}
        \"\"\"

        import enum

        class {opts.tag}(enum.{"IntEnum" if opts.mode & Mode.ENUM else "IntFlag"}):"""),
        file=opts.fout,
    )

    prefix = "" if not opts.leader else f"{opts.leader}_"
    if opts.mode & Mode.ENUM:
        _generate_enum_members(enum, opts.fout, prefix, maxlen, digits)
    else:
        _generate_mask_members(enum, opts.fout, prefix, maxlen, digits)
