metang (1)
==========

:manmanual: metang Manual
:mansource: metang {manversion}
:man-linkstyle: pass:[blue R < >]

NAME
----

metang - Generate enumerable constants for multiple languages

SYNOPSIS
--------

[verse]
'metang' [_OPTION_]... _FILE_
'metang' -h | --help
'metang' --version

DESCRIPTION
-----------

metang(1) is a metaprogramming utility for generating a consistent set of
enumerated constants; it accepts a sequence of symbols which represent such an
enumeration and emits a formal definition of that enumeration for a given
language. This is particularly useful for polyglot projects which must maintain
the same set of definitions across toolchains.

If the sequence of symbols is to be read from standard-input, then _FILE_ must
be specified as the hyphen character (_-_).

For details on the accepted syntax for the input sequence, see <<INPUT_SYNTAX>>.

OPTIONS
-------

`-b`::
`--bitmask`::
    Generate an enumerated bitmask. In this mode, the first symbol of the
    sequence is defined to be equivalent to _0_. Successive symbols are then
    defined to be equivalent to _1 << (i - 1)_, where _i_ is their position
    within the sequence and _<<_ is the left-directional bitwise shift operator.
    The final symbol is defined to be equivalent to _(1 << (i - 1)) - 1_, thus
    representing the bitwise logical disjunction (_OR_) of all previous symbols.

`-o OUTFILE`::
`--output=OUTFILE`::
    Write generated content to a file. If unspecified, then metang(1) will write
    all generated content to the standard-output stream. When specified, if the
    _--lang_ option is also unspecified, the extension of _OUTFILE_ will be used
    to guess the target language; see <<SUPPORTED_LANGUAGES>>.

`-l LANGUAGE`::
`--lang=LANGUAGE`::
    Generate the formal definition according to _LANGUAGE_. For details on the
    definitions generated by each supported value, see <<SUPPORTED_LANGUAGES>>.

`-t TAG`::
`--tag=TAG`::
    Use _TAG_ as an identifier for the generated definition and as a component
    for any other generated content. If unspecified, then the basename of the
    input file will be used, minus any file extension; no modifications are
    made to this derived-value to, e.g., convert punctuation marks to
    underscores.

`-g GUARD`::
`--guard=GUARD`::
    Use _GUARD_ as a prefix for any pre-processor-esque conditionals generated
    for the definition. If unspecified, then the default _METANG_ is used.

`-s SIZE`::
`--sized SIZE`::
    Bind the size and sign of the enum, if supported by the target language. If
    unspecified, then no type-bindings will be applied. *SIZE* is interpreted as
    a decimal value representing the sign and bit-width of the type-binding. For
    example, the C language will use fixed-width types from *stdint.h* and bind
    *SIZE == -8* to *int8_t*, *SIZE == 16* to *uint16_t*, etc.

`-h`::
`--help`::
    Display a summarized program help-text and exit.

`-v`::
`--version`::
    Display metang(1)'s version string and exit.

EXAMPLES
--------

`metang -`::
    Using per-line symbols from standard-input, write an enumeration to
    standard-output for the C language.

`metang input.txt`::
    Using per-line symbols from _input.txt_, write an enumeration to standard-
    output for the C language.

`metang -o output.hpp input.txt`::
    Write an enumeration to _output.hpp_ for the C++ language.

`metang -t MyEnum -o output.py input.txt`::
    Write an enumeration to _output.py_ for the Python language, definining its
    _class_ name as _MyEnum_.

`metang -l cpp -o output.h input.txt`::
    Write an enumeration to _output.h_ for the C++ language.

[[SUPPORTED_LANGUAGES]]
SUPPORTED LANGUAGES
-------------------

metang(1) supports generating definitions for multiple languages, though only
one language target may be specified per invocation. Each language target
generates content with a unique specification, and some languages will make use
of program options that others will not. All generated output is preceded by a
comment block recognized by the target which contains:

[start=1]
. A warning message stating that the file is generated, who generated it (that
  is, metang(1) itself), and that it should not be manually modified.
. The source file (or "stdin") containing the input sequence.
. A set of options which may be provided to metang(1) which will produce
  identical output from equivalent input. This set will contain all derived
  option arguments, per their individual behaviors.

The subsections below provide a summary of the content that is generated for
each supported target.

C Language
~~~~~~~~~~

Specified by using *--lang c* or providing an argument to *--output* which has
the extension *.h*. metang(1) uses this language as its preferred-default in
cases where the *--lang* option is not specified and the *--output* argument's
file extension is unrecognized. The generated definition is wrapped in the
C linkage specifier (*extern "C"*) for compatibility with C++ compilers and
contains the following sections:

. Preprocessor directive blocks which derives the C standard compliance of the
  user's compiler and the C standard version in use.
. An "enum" section, wrapped by *#ifdef <GUARD>_ENUM*. This section provides a
  definition of the input sequence as a tagged C *enum*. If a type-binding is
  provided via the `--sized` option, then a preprocessor block will also be
  emitted to determine if the user's compiler supports type-binding the *enum*.
  If the user of the generated *.h* file compiles with C23 or greater, the
  generated *enum* will be type-bound according to the following table:
+
[cols="1,1"]
|===
| *--sized* argument | *stdint.h* type
| *-8*               | *int8_t*
| *-16*              | *int16_t*
| *-32*              | *int32_t*
| *-64*              | *int64_t*
| *8*                | *uint8_t*
| *16*               | *uint16_t*
| *32*               | *uint32_t*
| *64*               | *uint64_t*
|===
+
. A "preproc" section to be used when *<GUARD>_ENUM* is not defined. This
  section generates an identical symbol-to-value mapping as the enum secition,
  but makes use of preprocessor *#define* directives instead of a C *enum*.
. A "lookup" section, wrapped by *#ifdef <GUARD>_LOOKUP*. This section declares
  a *struct* in the following format:
+
[source,c]
--------
typedef struct entry__<tag> {
    const char *name;
    const long value;
} entry__<tag>;
--------
+
Additionally, there are two subsections:

  .. An implementation subsection, wrapped by *#ifdef <GUARD>_LOOKUP_IMPL*.
     This subsection defines a binary-searchable lookup table *lookup__<tag>*
     as an array of the above *struct entry__<tag>* and the size of this
     lookup table as *long lengthof__<tag>*. This lookup table sorts the names
     of the symbols in lexicographic order to enable lookup via binary-search.
  .. A declaration subsection to be used when *<GUARD>_LOOKUP_IMPL* is not
     defined. This subsection defines *extern* symbols for the aforementioned
     *lookup__<tag>* and *lengthof__<tag>* for use by other translation units.

C++
~~~

Specified by using *--lang cpp* or providing an argument to *--output* which
has the extension *.hpp*. The generated definition contains the following
sections:

. A preprocessor directive block which derives the C++ standard in use. When
  the user of the generated *.hpp* file compiles with C++ 11 or greater, the
  generated *enum* in the following section will be declared as *enum struct*
  rather than *enum*, and -- if provided by the *--sized* option -- it will be
  type-bound to a fixed-width type defined by *<cstdint>*, as described in the
  earlier section for the C language.
. The definition of the C++ *enum*, with any corresponding qualifier and base-
  type.
. A "lookup" section, wrapped by *#ifdef <GUARD>_LOOKUP*. This section provides
  inclusions of *<map>* and *<string>* and contains two subsections:

  .. An implementation subsection, wrapped by *#ifdef <GUARD>_LOOKUP_IMPL*.
     This subsection defines a lookup table *lookup_<tag>* as a *std::map* with
     keys of type *std::string* and values of the same type as the generated
     *enum*.
  .. A declaration subsection to be used when *<GUARD>_LOOKUP_IMPL* is not
     defined. This subsection defines an *extern* symbols for the aforementioned
     *lookup_tag* for use by other translation units.

Python
~~~~~~

Specified by using *--lang py* or providing an argument *--output* which has the
extension *.py*. The generated definition is a Python *class* which derives
either *enum.IntEnum* (if *--bitmask* is *not* specified) or *enum.IntFlag* (if
*--bitmask* is specified).

[[INPUT_SYNTAX]]
INPUT SYNTAX
------------

Input is read as a newline-delimited list. For each entry within this list, the
following rules apply:

. An entry must always define its symbol. For simplicity and reproducibility, no
  validation or manipulation of the symbol is performed aside from stripping any
  leading or trailing whitespace.
. By default, the first entry implicitly begins with a value of *0*.
. Successor entries derive their values as an increment from their predecessor's
  value.
. Entries may specify a direct value assignment using an equals-sign (*=*). The
  right-hand-side of this operand is interpreted as a decimal integer literal or
  as a back-reference to a predecessor.
  * If the right-hand-side is an integer literal, then it is directly assigned
    as this symbol's value.
  * If the right-hand-value is a back-reference to a predecessor, then that
    predecessor's value is directly assigned as this symbol's value. If no such
    predecessor exists, then metang(1) will emit an error message and exit.
. The hash character (*#*) denotes that all succeeding text should be treated as
  a comment and ignored by any other processing.
. Comments are permitted on standalone lines or in-line.

BUGS
----

Report bugs to the project's issue page <lhearachel/metang.git[1]>. You will
need a GitHub account to create a new issue.

LICENSE
-------

Copyright \(C) 2025-present _lhearachel@proton.me_ +
Free use of this software is granted under the terms of the MIT License.

NOTES
-----

1. lhearachel/metang.git +
   https://github.com/lhearachel/metang
