.TH METANG 1
.SH NAME
.PP
metang \- generate multi\-purpose C headers for enumerators
.SH SYNOPSIS
.PP
\fB\fCmetang\fR \fB\fCCOMMAND\fR [\fB\fCOPTIONS\fR] [\fB\fC<FILE>\fR]
.SH DESCRIPTION
.PP
\fB\fCmetang\fR generates a customized C header of enumerated constants from a plain
text file. Each line of the input file is treated as another member of the
enumeration. It can generate enumerations of standard integer sequences, or
enumerations representative of a bit\-mask.
.SH COMMANDS
.TP
\fB\fCenum\fR
Generate an integer\-sequence enumeration.
.TP
\fB\fCmask\fR
Generate a bit\-mask enumeration.
.TP
\fB\fChelp\fR
Print help text and exit.
.TP
\fB\fCversion\fR
Print the program version number and exit.
.SH OPTIONS
.PP
The following options are available to all generators:
.TP
\fB\fC\-o\fR, \fB\fC\-\-output\fR \fB\fC<OFILE>\fR
Write output to \fB\fC<OFILE>\fR\&. If unspecified, then \fB\fCmetang\fR will write all
generated content to standard output.
.TP
\fB\fC\-l\fR, \fB\fC\-\-leader\fR \fB\fC<LEADER>\fR
Treat \fB\fC<LEADER>\fR as a prefix for generated enumeration symbols. If
unspecified, \fB\fC<LEADER>\fR will be derived from the output file's basename, minus
any extension. If the output stream points to standard output and this option
is not specified, then \fB\fC<LEADER>\fR will be derived as \fB\fCSTDOUT\fR\&. Any value
for \fB\fC<LEADER>\fR \-\- given or derived \-\- will be converted to \fB\fCUPPER_SNAKE_CASE\fR\&.
.TP
\fB\fC\-t\fR, \fB\fC\-\-tag\-name\fR \fB\fC<NAME>\fR
Use \fB\fC<NAME>\fR as the base name for the tag applied to the generated \fB\fCenum\fR,
lookup table member \fB\fCstruct\fR, and lookup table definition. If unspecified,
\fB\fC<NAME>\fR will be derived from the input file's basename, minus any extension.
If the input stream feeds from standard input and this option is not
specified, then \fB\fC<NAME>\fR will be derived as \fB\fCstdin\fR\&. Any value for this option
is treated literally; no special formatting or casing will be applied.
.TP
\fB\fC\-G\fR, \fB\fC\-\-guard\fR \fB\fC<GUARD>\fR
Use \fB\fC<GUARD>\fR as a prefix for all conditional directives. In C, this prefix is
applied to all inclusion guards.
.PP
The following options are available to integer\-sequence enumerations:
.TP
\fB\fC\-a\fR, \fB\fC\-\-append\fR \fB\fC<ENTRY>\fR
Append \fB\fC<ENTRY>\fR to the input listing.
.TP
\fB\fC\-p\fR, \fB\fC\-\-prepend\fR \fB\fC<ENTRY>\fR
Prepend \fB\fC<ENTRY>\fR to the input listing.
.TP
\fB\fC\-n\fR, \fB\fC\-\-start\-from\fR \fB\fC<NUMBER>\fR
Start the integer\-sequence enumeration from \fB\fC<NUMBER>\fR\&.
.PP
Additionally, integer\-sequence enumerations may directly assign the value of
member values in the input listing by appending \fB\fC= <NUMBER>\fR to the member name.
.SH AUTHOR
.PP
Rachel Forshee \[la]lhearachel@proton.me\[ra]
