name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Debug build
        run: make debug
      - name: Release build
        run: make release
      - name: Run tests
        run: make test
